version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: medtechchain-postgres
    profiles:
      - deps
      - dev
      - demo
    command: postgres
    environment:
      POSTGRES_DB: medtechchain
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - medtechchain
    volumes:
      - postgres_storage:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: medtechchain-pgadmin
    profiles:
      - deps
      - dev
      - demo
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@medtechchain.nl
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "10000:80"
    networks:
      - medtechchain
    volumes:
      - pgadmin_storage:/var/lib/pgadmin

  smtp4dev:
    image: rnwood/smtp4dev:3.3.2
    container_name: medtechchain-smtp4dev
    profiles:
      - deps
      - dev
    restart: always
    environment:
      ServerOptions__HostName: medtechchain.nl
    ports:
      - "11000:8080"
      - "25:25"
      - "143:143"
    networks:
      - medtechchain
    volumes:
      - smtp4dev_storage:/smtp4dev

  medtechchain-backend-dev: &medtechchain-backend-dev
    image: ${BE_IMAGE_NAME}
    container_name: medtechchain-backend
    depends_on:
      - postgres
    profiles:
      - dev
    environment: &medtechchain-backend-dev-env
      DB_POSTGRES_HOST: postgres
      SMTP_SERVER_HOST: smtp4dev
      CRYPTO_PATH: /home/user
      CERT_DIR_PATH: ./msp/signcerts
      KEY_DIR_PATH: ./msp/keystore
      TLS_CERT_PATH: ./tls/ca.crt
      PEER_ENDPOINT: peer0.medtechchain.nl:7051
      OVERRIDE_AUTH: peer0.medtechchain.nl
      CHANNEL_NAME: medtechchain
      CHAINCODE_NAME: medtechchain
      SMART_CONTRACT_NAME: medtechchain
    ports:
      - "8088:8088"
    networks:
      - medtechchain
    volumes:
      - ${LOCAL_USER_CRYPTO_PATH}:/home/user

  medtechchain-backend:
    <<: *medtechchain-backend-dev
    profiles:
      - demo
    environment:
      <<: *medtechchain-backend-dev-env
      SMTP_SERVER_HOST: smtp.gmail.com
      SMTP_SERVER_PORT: 587
      SMTP_USER: noreply.medtechchain@gmail.com
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_AUTH: "true"
      SMTP_TLS: "true"

networks:
  medtechchain:
    external: true
    name: medtechchain

volumes:
  postgres_storage:
  pgadmin_storage:
  smtp4dev_storage: