version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: medtechchain-postgres
    profiles:
      - deps
      - dev
      - demo
    command: postgres
    environment:
      - POSTGRES_DB=medtechchain
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    networks:
      - medtechchain-ums
    volumes:
      - postgres_storage:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.3
    container_name: medtechchain-pgadmin
    profiles:
      - deps
      - dev
      - demo
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@medtechchain.nl
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "10000:80"
    networks:
      - medtechchain-ums
    volumes:
      - pgadmin_storage:/var/lib/pgadmin

  smtp4dev:
    image: rnwood/smtp4dev:3.3.2
    container_name: medtechchain-smtp4dev
    profiles:
      - deps
      - dev
    restart: always
    environment:
      - ServerOptions__HostName=medtechchain.nl
    ports:
      - "11000:8080"
      - "25:25"
      - "143:143"
    networks:
      - medtechchain-ums
    volumes:
      - smtp4dev_storage:/smtp4dev

  medtechchain-backend-ums-dev: &medtechchain-backend-ums-dev
    image: ${BE_IMAGE_NAME}
    container_name: medtechchain-backend-ums
    depends_on:
      - postgres
    profiles:
      - dev
    environment:
      - DB_POSTGRES_HOST=postgres
      - SMTP_SERVER_HOST=smtp4dev
    ports:
      - "8088:8088"
    networks:
      - medtechchain-ums

  medtechchain-backend-ums:
    <<: *medtechchain-backend-ums-dev
    container_name: medtechchain-backend-ums
    profiles:
      - demo
    environment:
      - DB_POSTGRES_HOST=postgres
      - SMTP_SERVER_HOST=smtp.gmail.com
      - SMTP_SERVER_PORT=587
      - SMTP_USER=noreply.healthblocks@gmail.com
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_AUTH=true
      - SMTP_TLS=true

networks:
  medtechchain-ums:
    name: medtechchain-ums

volumes:
  postgres_storage:
  pgadmin_storage:
  smtp4dev_storage: