name: 'Run workflow'

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - '.github/workflows/workflow.yml'

  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - '.github/workflows/workflow.yml'

jobs:
  project-build:
    runs-on: ubuntu-latest

    steps:
        # Checkout the code
      - uses: actions/checkout@v4

        # Ensure the gradle-wrapper.jar file is legitimate
        # For explanations, see https://tomgregory.com/gradle/build-gradle-projects-with-github-actions/
      - uses: gradle/wrapper-validation-action@v2

        # Install Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle

      - name: Build
        run: ./gradlew build --no-daemon -x checkstyleMain -x checkstyleTest -x test

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Run Tests
        run: ./gradlew test
