name: 'Run workflow'

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/workflow.yml'

  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/workflow.yml'

jobs:
  project-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle

      - name: Build
        run: ./gradlew build -x checkstyleMain -x checkstyleTest -x test

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Run Tests
        run: ./gradlew test
